### ISSUE TITLE
Latest "update" fails to launch

### ISSUE THREAD

**Issue by Wryyyong** [xmoeproject/AlphaMovieDecoder#2]
I download the repository, I edit `first.ks` to whatever AMV I want to play, and try launching the program... and it closes one second later.

So then I try editing the selected AMV in `first.ks` to the file included in the repository (`particles.amv`) and relaunch the program. Same thing happens.

Then I proceeded to download an older version of the repository and try running that instead. It worked as intended, meaning something is off with the most recent commit.

So then I tried comparing code between different commits, and trying to find what was causing the issue, to no avail unfortunately.

I also learned that the program can now use an argument known as `-amvpath`, which appears to set the current script directory seeing as how it tries to look for `startup.tjs` first.

Point is, something's going wrong with the program, and I've been trying to pinpoint the exact problem for over 7 hours now with no result. If I could have some assistance with this it would be much appreciated.

**Comment by xmoezzz** [comment]
updated README

**Comment by Wryyyong** [comment]
Thank you kindlyyyyy
