### ISSUE TITLE
Packing

### ISSUE THREAD

**Issue by GribanovIvan** [xmoeproject/AlphaMovieDecoder#4]
xmoeproject for repacking games, yes? me need pack images to amv, how?

**Comment by GribanovIvan** [comment]
i find [that](http://kaede-software.com/krlm/plugin/) and [this](https://github.com/zhiyb/AlphaMovieEncoder)

**Comment by xmoezzz** [comment]
why not consider using the official packer...

**Comment by GribanovIvan** [comment]
> why not consider using the official packer...

where i can find it?
